[features]
seeds = false
skip-lint = false
[programs.localnet]
betting_game = "8G86yDJXRD6Pjoue42fq3ZgSsp3vL9hxrbSYWksgUi5q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yashjain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
